/*
NUI3 - C++ cross-platform GUI framework for OpenGL based applications
Copyright (C) 2002-2003 Sebastien Metrot & Vincent Caron

licence: see nui3/LICENCE.TXT
*/


#include "nui.h"

#include "DefaultDecoration/src/ArrowClose.cpp"
#include "DefaultDecoration/src/ArrowOpen.cpp"
#include "DefaultDecoration/src/ButtonDown.cpp"
#include "DefaultDecoration/src/ButtonUp.cpp"
#include "DefaultDecoration/src/CheckerboardSmall.cpp"
#include "DefaultDecoration/src/CloseButtonDown.cpp"
#include "DefaultDecoration/src/CloseButtonHover.cpp"
#include "DefaultDecoration/src/CloseButtonUp.cpp"
#include "DefaultDecoration/src/ComboDown.cpp"
#include "DefaultDecoration/src/ComboUp.cpp"
#include "DefaultDecoration/src/IconFile.cpp"
#include "DefaultDecoration/src/IconFolder.cpp"
#include "DefaultDecoration/src/IconOpenFolder.cpp"
#include "DefaultDecoration/src/IconParentFolder.cpp"
#include "DefaultDecoration/src/IconVolume.cpp"
#include "DefaultDecoration/src/ImageDraggedFile.cpp"
#include "DefaultDecoration/src/ImageDraggedFolder.cpp"
#include "DefaultDecoration/src/KnobSequenceHdl.cpp"
#include "DefaultDecoration/src/NavigationBarBlackButtonDown.cpp"
#include "DefaultDecoration/src/NavigationBarBlackButtonUp.cpp"
#include "DefaultDecoration/src/NavigationBarBlackLeftButtonDown.cpp"
#include "DefaultDecoration/src/NavigationBarBlackLeftButtonUp.cpp"
#include "DefaultDecoration/src/NavigationBarDefaultButtonDown.cpp"
#include "DefaultDecoration/src/NavigationBarDefaultButtonUp.cpp"
#include "DefaultDecoration/src/NavigationBarDefaultLeftButtonDown.cpp"
#include "DefaultDecoration/src/NavigationBarDefaultLeftButtonUp.cpp"
#include "DefaultDecoration/src/PaneInner.cpp"
#include "DefaultDecoration/src/PaneOutter.cpp"
#include "DefaultDecoration/src/PopupMenu.cpp"
#include "DefaultDecoration/src/RadioButtonDown.cpp"
#include "DefaultDecoration/src/RadioButtonDownDisabled.cpp"
#include "DefaultDecoration/src/RadioButtonUp.cpp"
#include "DefaultDecoration/src/RadioButtonUpDisabled.cpp"
#include "DefaultDecoration/src/ScrollbarHorizontalBkg.cpp"
#include "DefaultDecoration/src/ScrollbarHorizontalHdl.cpp"
#include "DefaultDecoration/src/ScrollbarMobile.cpp"
#include "DefaultDecoration/src/ScrollbarVerticalBkg.cpp"
#include "DefaultDecoration/src/ScrollbarVerticalHdl.cpp"
#include "DefaultDecoration/src/SliderHorizontalBkg.cpp"
#include "DefaultDecoration/src/SliderHorizontalHdl.cpp"
#include "DefaultDecoration/src/SliderVerticalBkg.cpp"
#include "DefaultDecoration/src/SliderVerticalHdl.cpp"
#include "DefaultDecoration/src/SplitterHorizontal.cpp"
#include "DefaultDecoration/src/SplitterHorizontalHandle.cpp"
#include "DefaultDecoration/src/SplitterVertical.cpp"
#include "DefaultDecoration/src/SplitterVerticalHandle.cpp"
#include "DefaultDecoration/src/TabBottomContents.cpp"
#include "DefaultDecoration/src/TabBottomDown.cpp"
#include "DefaultDecoration/src/TabBottomUp.cpp"
#include "DefaultDecoration/src/TabLeftContents.cpp"
#include "DefaultDecoration/src/TabLeftDown.cpp"
#include "DefaultDecoration/src/TabLeftUp.cpp"
#include "DefaultDecoration/src/TabRightContents.cpp"
#include "DefaultDecoration/src/TabRightDown.cpp"
#include "DefaultDecoration/src/TabRightUp.cpp"
#include "DefaultDecoration/src/TabTopContents.cpp"
#include "DefaultDecoration/src/TabTopDown.cpp"
#include "DefaultDecoration/src/TabTopUp.cpp"
#include "DefaultDecoration/src/ToggleButtonDown.cpp"
#include "DefaultDecoration/src/ToggleButtonDownDisabled.cpp"
#include "DefaultDecoration/src/ToggleButtonUp.cpp"
#include "DefaultDecoration/src/ToggleButtonUpDisabled.cpp"
