/* config.h.  NOT generated by configure, this one is hand crafted for a specific platform.  */

/* Define to 1 if you have the FreeType2 font library */
#define HAVE_FREETYPE 1

/* Define to 1 if you have the JPEG image library */
#define HAVE_LIBJPEG 1

/* Define to 1 if you have the libpng image library */
#define HAVE_LIBPNG 1

/* Define to 1 if you want MLANG (charset conversion) support */
#define HAVE_MLANG 0

/* Define to 1 if you want to use the CoreGraphics image library */
#define HAVE_COREGRAPHICS 1
